package util;

/*
 * 내가 이동하고싶은 화면 넣기
 */
public enum View {
	HOME, MAIN, 
	MEMBER, MEMBER_SIGNUP, MEMBER_LOGIN, MEMBER_RESIGN,
	BOARD , BOARD_LIST , BOARD_DETAIL,	BOARD_INSERT ,	BOARD_UPDATE, 
	ADMIN, PROD_MEMBER, PROD_ALL, PROD_MANAGE, PROD_REGIS, PROD_MOD, PROD_SOLDOUT, PROD_MOD2 , 
	
}
